version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    
    container_name: react-dev
    
    ports:
      - "5173:5173"
    
    volumes:
      - .:/app
      # This prevents node_modules in the container from being overwritten by the host
      - /app/node_modules
    
    environment:
      - NODE_ENV=development
      
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s